In [1]:
import torch

In [2]:
model = torch.nn.Linear(10, 1)

In [8]:
x = torch.zeros(10)
model(x)

tensor([-0.0757], grad_fn=<ViewBackward0>)

In [13]:
# Linear Binary Classification
class LinearClassifier(torch.nn.Module):
    def __init__(self, input_dim, output_dim) -> None:
        super().__init__()
        self.fc = torch.nn.Linear(input_dim, output_dim)

    def forward(self, x) -> torch.Tensor:
        return torch.nn.functional.sigmoid(self.fc(x))  # In practice, we shouldn't add this here as it is numerically unstable. We should do this outside this class when training our networks

model = LinearClassifier(10, 1)
x = torch.ones(10)
model(x)

tensor([0.3953], grad_fn=<SigmoidBackward0>)

In [18]:
# Linear Multi-Class Classification
class LinearClassifier(torch.nn.Module):
    def __init__(self, input_dim, n_classes) -> None:
        super().__init__()
        self.fc = torch.nn.Linear(input_dim, n_classes)

    def forward(self, x) -> torch.Tensor:
        # Do the softmax on the last dimension
        return torch.nn.functional.softmax(self.fc(x), dim=-1) # In practice, we shouldn't add this here as it is numerically unstable. We should do this outside this class when training our networks

model = LinearClassifier(10, 4)
x = torch.ones(10)
model(x)

tensor([0.0897, 0.8214, 0.0417, 0.0473], grad_fn=<SoftmaxBackward0>)