In [1]:
import torch

In [6]:
x = torch.rand(10, requires_grad=True)
x

tensor([0.9577, 0.9694, 0.0195, 0.9801, 0.5764, 0.0411, 0.0385, 0.2606, 0.7839,
        0.8871], requires_grad=True)

In [23]:
b = (x**2).mean()
print(b)
b.backward() # We can call backward() only once. We have to redefine `b` again to run backward() again
print(x)
print(x.grad)

tensor(0.4623, grad_fn=<MeanBackward0>)
tensor([0.9577, 0.9694, 0.0195, 0.9801, 0.5764, 0.0411, 0.0385, 0.2606, 0.7839,
        0.8871], requires_grad=True)
tensor([1.9153, 1.9388, 0.0391, 1.9602, 1.1528, 0.0821, 0.0770, 0.5212, 1.5678,
        1.7742])


In [ ]:
torch.cuda.memory_allocated()
x = torch.rand(10, requires_grad=True, device='cuda')

AssertionError: Torch not compiled with CUDA enabled