In [1]:
import torch

In [2]:
model = torch.nn.Linear(10, 1)

In [4]:
# Create a random dataset
x = torch.randn(20, 10)
y = torch.randn(20, 1)
print(f'{x=} {y=}')

x=tensor([[-0.1668, -0.4933,  0.0553, -1.9558,  0.7145, -0.3047,  0.3821, -0.1001,
         -1.3081,  2.2872],
        [-0.9478, -0.3660, -0.2879,  0.5468,  0.3305, -1.0989, -0.9752,  0.1009,
          1.6604,  0.1770],
        [ 1.5685,  0.5307, -0.0988, -0.2243,  0.1477,  0.1746, -0.1415, -0.9044,
         -0.8623, -1.7588],
        [-0.4879, -0.4711,  0.8299, -0.1260,  0.7085, -0.7535, -2.6868,  2.4048,
         -0.0134, -0.5823],
        [ 0.2641, -1.0960,  0.0218,  1.0555,  1.5332, -0.7671, -0.1570,  0.6562,
         -0.6593, -0.8071],
        [ 2.0274,  0.5738,  0.6846,  0.3827,  0.2613, -0.7169,  0.1843, -0.1534,
         -0.5392,  0.7915],
        [ 2.1574, -1.3566, -0.3219, -1.7855, -1.0466,  1.5040, -0.4585,  0.9308,
          0.6859, -0.8177],
        [-0.4447, -0.3602, -0.6891, -0.2494, -0.5876, -0.5441, -0.1897,  0.0665,
         -0.1318,  1.2119],
        [ 1.6757, -1.0197,  0.8368,  0.9534, -0.2253, -0.3606, -1.3000, -1.1262,
          1.1972, -0.7318],
        [-0.0094,

In [5]:
pred_y = model(x)
print(pred_y)

tensor([[ 0.2217],
        [-0.1005],
        [-0.2605],
        [ 0.0949],
        [-0.5224],
        [ 0.1850],
        [-0.4291],
        [ 0.2619],
        [-0.2394],
        [ 0.0722],
        [-0.1549],
        [-0.1430],
        [-0.4100],
        [ 0.0786],
        [-0.4302],
        [-0.5072],
        [ 0.3808],
        [-0.8224],
        [-1.2032],
        [-0.1649]], grad_fn=<AddmmBackward0>)


In [7]:
# Compare our values (y) with the predicted values (pred_y)
loss = torch.nn.functional.mse_loss(pred_y, y)
print(loss)

tensor(0.6507, grad_fn=<MseLossBackward0>)


In [9]:
def mse_loss(pred_y, y):
    return torch.mean((pred_y - y) ** 2)
mse_loss(pred_y, y)

tensor(0.6507, grad_fn=<MeanBackward0>)

In [13]:
# Binary Classification
y = (torch.randn(20, 1) > 0).float()
print(y)

tensor([[1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.]])


In [15]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(pred_y, y) # Using this method allows us to use the linear model we previously defined without needing to add the sigmoid. This method will add the sigmoid and then evaluate the loss
print(loss)

tensor(0.6838, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [22]:
# Multi-class classification
n_classes = 3
model = torch.nn.Linear(10, n_classes)
y = (torch.randn(20) > 0).long() + (torch.randn(20) > 0).long() # We add them to get three labels: [0, 1, 2]
print(y)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 2, 1, 2])


In [24]:
pred_y = model(x)
loss = torch.nn.functional.cross_entropy(pred_y, y) # Again, have the loss function compute the softmax, never add it to the model
print(loss)

tensor(1.0865, grad_fn=<NllLossBackward0>)
