In [1]:
import torch
import torch.distributions as dist

In [3]:
bernoulli = dist.Bernoulli(torch.tensor([0.5]))  # Create a Bernoulli distribution with 50% probability of producing a 0, and equivalently producing a 1

for _ in range(10):
    print(bernoulli.sample())

tensor([0.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([0.])


In [4]:
samples = [bernoulli.sample() for _ in range(1000)]
print(f'Mean: {torch.mean(torch.stack(samples))}')
print(f'Variance: {torch.var(torch.stack(samples))}')

Mean: 0.48399999737739563
Variance: 0.24999399483203888


If we look at the actual mean, in theory it should be 0.5, but it isn't


In [5]:
normal = dist.Normal(torch.tensor([0.0]), torch.tensor([1.0]))  # Create a Normal distribution
for _ in range(10):
    print(normal.sample())

tensor([-0.3568])
tensor([-1.5360])
tensor([-0.1122])
tensor([-2.7131])
tensor([-0.5188])
tensor([0.8649])
tensor([0.0178])
tensor([-1.0213])
tensor([-1.3732])
tensor([-2.3622])


In [6]:
samples = [normal.sample() for _ in range(1000)]
print(f'Mean: {torch.mean(torch.stack(samples))}')
print(f'Variance: {torch.var(torch.stack(samples))}')

Mean: -0.021241486072540283
Variance: 0.9747005105018616


Again, if we look at the mean, it is not te same as the one we specified. The samples never fully match the original distribution