In [2]:
import torch

In [9]:
a = torch.tensor([1, 2, 3], dtype=torch.float32)
print(a)

tensor([1., 2., 3.])


In [14]:
# We can create tensors without specifying any specific values, only the shape of the tensor
b = torch.rand([3, 3, 3], dtype=torch.float32)
print(b)

tensor([[[0.3308, 0.0468, 0.0326],
         [0.4510, 0.9656, 0.4508],
         [0.2949, 0.0911, 0.4987]],

        [[0.5263, 0.3654, 0.1514],
         [0.6242, 0.0836, 0.1727],
         [0.8309, 0.5263, 0.6012]],

        [[0.4400, 0.6342, 0.5904],
         [0.1373, 0.2248, 0.8016],
         [0.2711, 0.1327, 0.0639]]])


In [24]:
# We can also load a tensor from an image
from PIL import Image
import numpy as np

img = Image.open('cat.jpg')
c = torch.as_tensor(np.array(img))
print(c)

tensor([[[106, 102,  99],
         [109, 105, 102],
         [113, 109, 106],
         ...,
         [ 46,  45,  41],
         [ 45,  44,  40],
         [ 44,  43,  39]],

        [[106, 102,  99],
         [109, 105, 102],
         [113, 109, 106],
         ...,
         [ 46,  45,  41],
         [ 45,  44,  40],
         [ 44,  43,  39]],

        [[105, 101,  98],
         [108, 104, 101],
         [112, 108, 105],
         ...,
         [ 46,  45,  41],
         [ 45,  44,  40],
         [ 44,  43,  39]],

        ...,

        [[127, 123, 120],
         [126, 122, 119],
         [125, 121, 118],
         ...,
         [ 41,  36,  33],
         [ 40,  36,  33],
         [ 40,  36,  33]],

        [[127, 123, 120],
         [126, 122, 119],
         [125, 121, 118],
         ...,
         [ 41,  36,  33],
         [ 40,  36,  33],
         [ 40,  36,  33]],

        [[127, 123, 120],
         [126, 122, 119],
         [125, 121, 118],
         ...,
         [ 39,  35,  32],
        

In [29]:
a = torch.arange(10)
b = torch.ones(10)
print(f'{a = }')
print(f'{b = }')
print(f'{a + b = }')
print(f'{a - b = }')
print(f'{a * b = }')
print(f'{a / b = }')
print(f'{a ** (2*b) = }')

a = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
a + b = tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
a - b = tensor([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])
a * b = tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
a / b = tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
a ** (2*b) = tensor([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])


We must always verify that tensors have the same shape (unless we are broadcasting)

In [31]:
a = torch.rand(500_000_000)
b = torch.rand(500_000_000)
c = a + b

In [33]:
# We can add two big tensors and time it
%timeit c = a + b

The slowest run took 6.06 times longer than the fastest. This could mean that an intermediate result is being cached.
135 ms ± 121 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [37]:
# We can offload computation to a GPU
# TODO: Enable CUDA
a_gpu = a.to('cuda')
b_gpu = b.to('cuda')
%timeit c_gpu = a_gpu + b_gpu

AssertionError: Torch not compiled with CUDA enabled

In [41]:
# We can change the shape of a tensor
a = torch.arange(6)

print(a.view(2, 3))  # This will not copy the underlying data
print(a.reshape(2, 3))  # This will copy the underlying data

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [43]:
# We can transpose a matrix
a = torch.rand(2, 3)
print(a)
print(a.mT)

tensor([[0.9130, 0.6760, 0.2907],
        [0.1506, 0.4060, 0.7699]])
tensor([[0.9130, 0.1506],
        [0.6760, 0.4060],
        [0.2907, 0.7699]])


In [45]:
# We can permute dimensions
a = torch.rand(2, 3, 4)
print(a.permute(1, 2, 0).shape)

torch.Size([3, 4, 2])


In [49]:
# We can add dimensions to a tensor
a = torch.arange(6)
print(a[None].shape) # Add a dimension of size 1 at the beginning
print(a[:, None].shape) # Add a dimension of size 1 at the end
print(a[None, :, None].shape) # Add a dimension of size 1 at the beginning and at the end

torch.Size([1, 6])
torch.Size([6, 1])
torch.Size([1, 6, 1])


In [51]:
# We can remove dimensions from a tensor as long as they are of size 1
a = torch.arange(6).view(3, 2, 1, 1)
print(a.squeeze(-1).shape) # Remove the last dimension
print(a.squeeze().shape) # This will remove all dimensions of size 1. We should never do this as it is dangerous

torch.Size([3, 2, 1])
torch.Size([3, 2])


In [55]:
# BROADCASTING
# We can add tensors of different dimensions as long as we add them along a dimension of size 1. This is called broadcasting
a = torch.arange(4).view(4, 1)
b = torch.arange(5).view(1, 5)*10
print(f'{a = }')
print(f'{b = }')
print(a + b)
print(a * b) # Outer product
print(a - b)

a = tensor([[0],
        [1],
        [2],
        [3]])
b = tensor([[ 0, 10, 20, 30, 40]])
tensor([[ 0, 10, 20, 30, 40],
        [ 1, 11, 21, 31, 41],
        [ 2, 12, 22, 32, 42],
        [ 3, 13, 23, 33, 43]])
tensor([[  0,   0,   0,   0,   0],
        [  0,  10,  20,  30,  40],
        [  0,  20,  40,  60,  80],
        [  0,  30,  60,  90, 120]])
tensor([[  0, -10, -20, -30, -40],
        [  1,  -9, -19, -29, -39],
        [  2,  -8, -18, -28, -38],
        [  3,  -7, -17, -27, -37]])


In [61]:
# Simple examples of broadcasting
x = torch.randn(10, 2)
d = torch.zeros(10, 10)
max_dist, max_idx = 0, (-1, -1)
for i in range(10):
    for j in range(10):
        if (x[i] - x[j]).pow(2).sum() > max_dist:
            max_dist, max_idx = (x[i] - x[j]).pow(2).sum(), (i, j)

print(max_dist, max_idx)

d = (x[:, None, :] - x[None, :, :]).pow(2).sum(-1)
print(d.max(), (d.argmax() // 10, d.argmax() % 10))

tensor(13.2381) (1, 5)
tensor(13.2381) (tensor(1), tensor(5))


In [67]:
# Matrix multiplication between two matrices
a = torch.rand(2, 4)
b = torch.rand(4)
c = b @ a.mT
print(c.shape)
print(torch.linalg.norm(b))

torch.Size([2])
tensor(1.1906)
